version: "3.7"

services:
    rabbit1:
        image: rabbitmq:3-management
        hostname: rabbit1
        environment:
            RABBITMQ_ERLANG_COOKIE: "secret string"
            RABBITMQ_NODENAME: rabbit1
        volumes:
            - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
            - "./definitions.json:/etc/rabbitmq/definitions.json"
        ports:
            - "4369:4369"
            - "5671:5671"
            - "5672:5672"
            - "15671:15671"
            - "15672:15672"
            - "25672:25672"
        network_mode: rabbitmq-cluster

    redis:
        image: "redis:latest"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "6379:6379"
        network_mode: redis-cluster

    PostgreSQL:
        restart: always
        image: sameersbn/postgresql:10-2
        ports:
            - "5432:5432"
        network_mode: bridge
        environment:
            - DEBUG=false

            - DB_USER=integrator
            - DB_PASS=inteword
            - DB_NAME=locationservice
            - DB_TEMPLATE=

            - DB_EXTENSION=

            - REPLICATION_MODE=
            - REPLICATION_USER=
            - REPLICATION_PASS=
            - REPLICATION_SSLMODE=
        volumes:
            - /srv/docker/postgresql:/var/lib/postgresql

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        network_mode: bridge
        restart: unless-stopped

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
        container_name: elasticsearch
        environment:
            - node.name=elasticsearch
            - cluster.name=datasearch
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - cluster.initial_master_nodes=elasticsearch
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
    
    kibana:
        image: docker.elastic.co/kibana/kibana:7.0.1
        ports:
            - "5601:5601"