version: "3.7"

services:
    rabbit1:
        image: rabbitmq:3-management
        hostname: rabbit1
        environment:
            RABBITMQ_ERLANG_COOKIE: "secret string"
            RABBITMQ_NODENAME: rabbit1
        volumes:
            - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
            - "./definitions.json:/etc/rabbitmq/definitions.json"
        ports:
            - "4369:4369"
            - "5671:5671"
            - "5672:5672"
            - "15671:15671"
            - "15672:15672"
            - "25672:25672"
        network_mode: rabbitmq-cluster

    redis:
        image: "redis:latest"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "6379:6379"
        network_mode: redis-cluster